### ISSUE TITLE
Modify it to work on windows as well

### ISSUE THREAD

**Issue by bradleylandis** [drihu/poketask#4]
This works great on my linux machine but does not work at all on windows.

**Comment by bradleylandis** [comment]
npm install -g poketask
C:\Program Files\nodejs\poketask -> C:\Program Files\nodejs\node_modules\poketask\lib\poketask.js

> poketask@0.4.5 install C:\Program Files\nodejs\node_modules\poketask
> npm run remove; npm run clone:git; npm run clone:lic

npm ERR! missing script: remove;
npm ERR!
npm ERR! Did you mean this?
npm ERR!     remove

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Blandis\AppData\Roaming\npm-cache\_logs\2019-02-21T21_10_35_097Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poketask@0.4.5 install: `npm run remove; npm run clone:git; npm run clone:lic`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poketask@0.4.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Blandis\AppData\Roaming\npm-cache\_logs\2019-02-21T21_10_38_115Z-debug.log

**Comment by bradleylandis** [comment]
pull request submitted

**Comment by drihu** [comment]
I've added the scripts, thanks.
